description: "A new Flutter project."
name: "employee_byte"
publish_to: "none"
version: "1.0.0+1"
dependencies:
  animations: ^2.0.0
  date_format: ^2.0.2
  flutter:
    sdk: flutter
  flutter_typeahead: ^3.1.1
  get: ^4.1.4
  image_picker: ^0.7.4
  path: ^1.8.0
  path_provider: ^2.0.1
  sembast: ^3.0.1
  url_launcher: ^6.0.3

dev_dependencies:
  lint: ^1.5.3
  flutter_test:
    sdk: flutter
environment:
  sdk: ">=2.12.0 <3.0.0"
flutter:
  fonts:
    - family: "Roboto Condensed"
      fonts:
        - asset: "assets/fonts/Roboto-Condensed/Roboto-Condensed-300i.ttf"
          style: "italic"
          weight: 300
        - asset: "assets/fonts/Roboto-Condensed/Roboto-Condensed-400i.ttf"
          style: "italic"
          weight: 400
        - asset: "assets/fonts/Roboto-Condensed/Roboto-Condensed-700i.ttf"
          style: "italic"
          weight: 700
        - asset: "assets/fonts/Roboto-Condensed/Roboto-Condensed-300.ttf"
          weight: 300
        - asset: "assets/fonts/Roboto-Condensed/Roboto-Condensed-400.ttf"
          weight: 400
        - asset: "assets/fonts/Roboto-Condensed/Roboto-Condensed-700.ttf"
          weight: 700
    - family: "Open Sans"
      fonts:
        - asset: "assets/fonts/Open-Sans/Open-Sans-300i.ttf"
          style: "italic"
          weight: 300
        - asset: "assets/fonts/Open-Sans/Open-Sans-400i.ttf"
          style: "italic"
          weight: 400
        - asset: "assets/fonts/Open-Sans/Open-Sans-600i.ttf"
          style: "italic"
          weight: 600
        - asset: "assets/fonts/Open-Sans/Open-Sans-700i.ttf"
          style: "italic"
          weight: 700
        - asset: "assets/fonts/Open-Sans/Open-Sans-800i.ttf"
          style: "italic"
          weight: 800
        - asset: "assets/fonts/Open-Sans/Open-Sans-300.ttf"
          weight: 300
        - asset: "assets/fonts/Open-Sans/Open-Sans-400.ttf"
          weight: 400
        - asset: "assets/fonts/Open-Sans/Open-Sans-600.ttf"
          weight: 600
        - asset: "assets/fonts/Open-Sans/Open-Sans-700.ttf"
          weight: 700
        - asset: "assets/fonts/Open-Sans/Open-Sans-800.ttf"
          weight: 800
  uses-material-design: true
